ALTER TABLE songs ADD COLUMN album TEXT;
ALTER TABLE songs ADD COLUMN genre TEXT;
ALTER TABLE songs ADD COLUMN year TEXT;
ALTER TABLE songs ADD COLUMN codec TEXT;
ALTER TABLE songs ADD COLUMN sample_rate INTEGER;
ALTER TABLE songs ADD COLUMN channels INTEGER;
ALTER TABLE songs ADD COLUMN bitrate INTEGER;
ALTER TABLE songs ADD COLUMN language TEXT;